/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ElpisHeroMarketplaceEventsInterface extends utils.Interface {
  contractName: "ElpisHeroMarketplaceEvents";
  functions: {};

  events: {
    "ElpisHeroOwnershipChanged(uint256,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ElpisHeroOwnershipChanged"): EventFragment;
}

export type ElpisHeroOwnershipChangedEvent = TypedEvent<
  [BigNumber, string, string],
  {
    tokenId: BigNumber;
    ownerBeforeOwnershipTransferred: string;
    ownerAfterOwnershipTransferred: string;
  }
>;

export type ElpisHeroOwnershipChangedEventFilter =
  TypedEventFilter<ElpisHeroOwnershipChangedEvent>;

export interface ElpisHeroMarketplaceEvents extends BaseContract {
  contractName: "ElpisHeroMarketplaceEvents";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ElpisHeroMarketplaceEventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "ElpisHeroOwnershipChanged(uint256,address,address)"(
      tokenId?: null,
      ownerBeforeOwnershipTransferred?: null,
      ownerAfterOwnershipTransferred?: null
    ): ElpisHeroOwnershipChangedEventFilter;
    ElpisHeroOwnershipChanged(
      tokenId?: null,
      ownerBeforeOwnershipTransferred?: null,
      ownerAfterOwnershipTransferred?: null
    ): ElpisHeroOwnershipChangedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
