/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ElpisHeroDataStoragesInterface extends utils.Interface {
  contractName: "ElpisHeroDataStorages";
  functions: {
    "elpisHeroesData(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "elpisHeroesData",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "elpisHeroesData",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ElpisHeroDataStorages extends BaseContract {
  contractName: "ElpisHeroDataStorages";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ElpisHeroDataStoragesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    elpisHeroesData(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, string, BigNumber] & {
        elpisHeroId: BigNumber;
        elpisHeroName: string;
        ownerAddress: string;
        heroPrice: BigNumber;
        status: string;
        reputation: BigNumber;
      }
    >;
  };

  elpisHeroesData(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, BigNumber, string, BigNumber] & {
      elpisHeroId: BigNumber;
      elpisHeroName: string;
      ownerAddress: string;
      heroPrice: BigNumber;
      status: string;
      reputation: BigNumber;
    }
  >;

  callStatic: {
    elpisHeroesData(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, string, BigNumber] & {
        elpisHeroId: BigNumber;
        elpisHeroName: string;
        ownerAddress: string;
        heroPrice: BigNumber;
        status: string;
        reputation: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    elpisHeroesData(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    elpisHeroesData(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
