/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ElpisHeroMarketplaceEvents,
  ElpisHeroMarketplaceEventsInterface,
} from "../ElpisHeroMarketplaceEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "ownerBeforeOwnershipTransferred",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "ownerAfterOwnershipTransferred",
        type: "address",
      },
    ],
    name: "ElpisHeroOwnershipChanged",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50601680601d6000396000f3fe6080604052600080fdfea164736f6c6343000804000a";

type ElpisHeroMarketplaceEventsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ElpisHeroMarketplaceEventsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ElpisHeroMarketplaceEvents__factory extends ContractFactory {
  constructor(...args: ElpisHeroMarketplaceEventsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "ElpisHeroMarketplaceEvents";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ElpisHeroMarketplaceEvents> {
    return super.deploy(overrides || {}) as Promise<ElpisHeroMarketplaceEvents>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ElpisHeroMarketplaceEvents {
    return super.attach(address) as ElpisHeroMarketplaceEvents;
  }
  connect(signer: Signer): ElpisHeroMarketplaceEvents__factory {
    return super.connect(signer) as ElpisHeroMarketplaceEvents__factory;
  }
  static readonly contractName: "ElpisHeroMarketplaceEvents";
  public readonly contractName: "ElpisHeroMarketplaceEvents";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ElpisHeroMarketplaceEventsInterface {
    return new utils.Interface(_abi) as ElpisHeroMarketplaceEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ElpisHeroMarketplaceEvents {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ElpisHeroMarketplaceEvents;
  }
}
